// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225065850_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IT",
                            Description = "IT Department",
                            IsDeleted = false,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HR",
                            Description = "HR Department",
                            IsDeleted = false,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FINANCE",
                            Description = "Finance Department",
                            IsDeleted = false,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SALES",
                            Description = "Sales Department",
                            IsDeleted = false,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 5,
                            Code = "OPS",
                            Description = "Operations Department",
                            IsDeleted = false,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("Backend.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalaryRange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("DepartmentId", "IsDeleted");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalaryRange = 50000m,
                            Code = "SE",
                            DepartmentId = 1,
                            Description = "Software Development Role",
                            IsDeleted = false,
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalaryRange = 80000m,
                            Code = "SM",
                            DepartmentId = 1,
                            Description = "Senior Management Role",
                            IsDeleted = false,
                            Title = "Senior Manager"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalaryRange = 60000m,
                            Code = "HRM",
                            DepartmentId = 2,
                            Description = "HR Management Role",
                            IsDeleted = false,
                            Title = "HR Manager"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalaryRange = 70000m,
                            Code = "FM",
                            DepartmentId = 3,
                            Description = "Finance Management Role",
                            IsDeleted = false,
                            Title = "Finance Manager"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalaryRange = 55000m,
                            Code = "SET",
                            DepartmentId = 4,
                            Description = "Sales Role",
                            IsDeleted = false,
                            Title = "Sales Executive"
                        });
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("DepartmentId", "IsDeleted");

                    b.HasIndex("DesignationId", "IsDeleted");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            DesignationId = 1,
                            Email = "john.smith@company.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            DesignationId = 3,
                            Email = "jane.doe@company.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            DesignationId = 4,
                            Email = "robert.johnson@company.com",
                            FirstName = "Robert",
                            IsDeleted = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            DesignationId = 5,
                            Email = "michael.brown@company.com",
                            FirstName = "Michael",
                            IsDeleted = false,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            DesignationId = 2,
                            Email = "sarah.wilson@company.com",
                            FirstName = "Sarah",
                            IsDeleted = false,
                            LastName = "Wilson"
                        });
                });

            modelBuilder.Entity("Backend.Models.EmployeeSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allowances")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("HRA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("EmployeeId", "IsDeleted");

                    b.ToTable("EmployeeSalaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allowances = 2000m,
                            BaseSalary = 50000m,
                            DA = 5000m,
                            EmployeeId = 1,
                            HRA = 10000m,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Allowances = 2500m,
                            BaseSalary = 60000m,
                            DA = 6000m,
                            EmployeeId = 2,
                            HRA = 12000m,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Allowances = 3000m,
                            BaseSalary = 70000m,
                            DA = 7000m,
                            EmployeeId = 3,
                            HRA = 14000m,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Allowances = 2200m,
                            BaseSalary = 55000m,
                            DA = 5500m,
                            EmployeeId = 4,
                            HRA = 11000m,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Allowances = 3500m,
                            BaseSalary = 80000m,
                            DA = 8000m,
                            EmployeeId = 5,
                            HRA = 16000m,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Backend.Models.Designation", b =>
                {
                    b.HasOne("Backend.Models.Department", "Department")
                        .WithMany("Designations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("Backend.Models.EmployeeSalary", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Navigation("Designations");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Backend.Models.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Navigation("EmployeeSalaries");
                });
#pragma warning restore 612, 618
        }
    }
}
